services:
  store-frontend:
    image: sebastianlachut/store-frontend:1.0.0
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://products-api:8080
    depends_on:
      - products-api

  products-api:
    image: sebastianlachut/products-api:1.0.0
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=store
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE_NAME=notifications
    depends_on:
      - db
      - rabbitmq

  notifications-api:
    image: sebastianlachut/notification-api:1.0.0
    ports:
      - "5001:5001"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE_NAME=notifications
    depends_on:
      - rabbitmq

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: store
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  db_data: