apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
  namespace: store-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: sebastianlachut/products-api:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: "db"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "example"
            - name: MYSQL_DATABASE
              value: "store"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_QUEUE_NAME
              value: "notifications"
